version: '3.2'

services:
  api-front:
    image: gblbjj/myfeed:1.0.0
    ports:
      - "5000:5000"
    networks:
      - jarvis-net  
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]  

networks:
  jarvis-net:
    driver: overlay
        