version: '3.2'

services:
  app-myfeed:
    image: gblbjj/myfeed:1.0.0
    hostname: myfeed
    ports:
      - "5000:5000"
    networks:
      - redzone-net  
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]  

  # nginx:
  #   image: nginx:1.19.5
        
networks:
  redzone-net:
    driver: overlay
  
        